# Spring App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springapp
          image: "{{ .Values.springapp.image.repository }}:{{ .Values.springapp.image.tag }}"
          ports:
            - containerPort: {{ .Values.springapp.service.targetPort }}
          env:
            - name: MONGO_DB_HOSTNAME
              value: "{{ .Values.springapp.env.MONGO_DB_HOSTNAME }}"
            - name: MONGO_DB_USERNAME
              value: "{{ .Values.springapp.env.MONGO_DB_USERNAME }}"
            - name: MONGO_DB_PASSWORD
              value: "{{ .Values.springapp.env.MONGO_DB_PASSWORD }}"

---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image }}"
          ports:
            - containerPort: {{ .Values.mongodb.service.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.mongodb.env.MONGO_INITDB_ROOT_USERNAME }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{ .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD }}"

