apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  mongo-user: admin
  mongo-password: password123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mongo

  template:
    metadata:
      labels:
        app: mongo

    spec:
      containers:
      - name: mongo
        image: mongo:6.0

        ports:
        - containerPort: 27017

        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user

        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password

---
apiVersion: v1
kind: Service
metadata:
  name: mongo

spec:
  selector:
    app: mongo

  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: springboot-app

  template:
    metadata:
      labels:
        app: springboot-app

    spec:
      containers:
      - name: springboot-app
        image: karthik56t/mongospring:latest

        ports:
        - containerPort: 8080

        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: mongo

        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"

        - name: SPRING_DATA_MONGODB_DATABASE
          value: admin

        - name: SPRING_DATA_MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user

        - name: SPRING_DATA_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password

        - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
          value: admin

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service

spec:
  type: LoadBalancer

  selector:
    app: springboot-app

  ports:
  - port: 80
    targetPort: 8080
