replicaCount: 2

springapp:
  image:
    repository: kkeducation12345/spring-app
    tag: 1.0.0
  service:
    type: NodePort
    port: 80
    targetPort: 8080
  env:
    MONGO_DB_HOSTNAME: "mongosvc"
    MONGO_DB_USERNAME: "devdb"
    MONGO_DB_PASSWORD: "devdb@123"

mongodb:
  image: mongo
  replicaCount: 1
  service:
    type: ClusterIP
    port: 27017
  env:
    MONGO_INITDB_ROOT_USERNAME: "devdb"
    MONGO_INITDB_ROOT_PASSWORD: "devdb@123"
  storage:
    size: 1Gi
    storageClass: gp2
